### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by samcarswell** [josa42/coc-lua#103]
Getting the following error when opening a lua file:

```log
## versions

vim version: NVIM v0.10.0
node version: v20.12.2
coc.nvim version: 0.0.82-e4abae7b 2024-06-26 09:56:15 +0800
coc.nvim directory: /home/srcarswell/.local/share/nvim/lazy/coc.nvim
term: WezTerm
platform: linux

## Log of coc.nvim

2024-06-27T18:32:38.006 INFO (pid:11614) [plugin] - coc.nvim initialized with node: v20.12.2 after 327
2024-06-27T18:32:39.400 ERROR (pid:11614) [extensions-manager] - Error on active extension coc-lua: TypeError: Cannot read properties of undefined (reading 'find')
    at /home/srcarswell/.config/coc/extensions/node_modules/coc-lua/lib/utils/installer.js:32:60
    at Generator.next (<anonymous>)
    at fulfilled (/home/srcarswell/.config/coc/extensions/node_modules/coc-lua/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-27T18:32:39.406 ERROR (pid:11614) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'find')
      at /home/srcarswell/.config/coc/extensions/node_modules/coc-lua/lib/utils/installer.js:32:60
      at Generator.next (<anonymous>)
      at fulfilled (/home/srcarswell/.config/coc/extensions/node_modules/coc-lua/node_modules/tslib/tslib.js:166:62)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} TypeError: Cannot read properties of undefined (reading 'find')
    at /home/srcarswell/.config/coc/extensions/node_modules/coc-lua/lib/utils/installer.js:32:60
    at Generator.next (<anonymous>)
    at fulfilled (/home/srcarswell/.config/coc/extensions/node_modules/coc-lua/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-27T18:32:44.160 ERROR (pid:11614) [timing] - activate coc-lua timeout after 5000ms
2024-06-27T18:32:45.350 INFO (pid:11614) [attach] - Request action: fillDiagnostics [ 3 ]
2024-06-27T18:32:51.367 INFO (pid:11614) [attach] - receive notification: showInfo []

```

**Comment by samcarswell** [comment]
Seems to have gone away on It's own.
