### ISSUE TITLE
Error on active extension coc-lua: Error: Windows is not currently supported

### ISSUE THREAD

**Issue by hugobarroca** [josa42/coc-lua#104]
Sorry if this is an obvious question, but I've run into an error trying to install coc-lua in Windows 11, and I can't tell if this is supposed to happen or not.

When doing a :CocInstall coc-lua , and then opening a .lua file, I get the error message "Windows is not currently supported".
After searching the code, I've found the message seems to be coming from the installer.ts file, speficially for win32 operating systems.

That said, looking at previous issues, and the readme, it seems like Windows is supposed to work normally with this extention. Am I not following the proper installation method? I've managed to get the language server  working by installing it with Mason and manually setting it up in coc-settings, but I thought I'd at least post it here in case someone else runs into this...

My setup consists of Windows 11, nvim with lazy.vim, mason and coc.

```lua
2024-09-09T20:03:55.133 INFO (pid:45888) [plugin] - coc.nvim initialized with node: v20.12.2 after 129
2024-09-09T20:04:01.123 ERROR (pid:45888) [extensions-manager] - Error on active extension coc-lua: Error: Windows is not currently supported
    at C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\lib\utils\installer.js:56:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\node_modules\tslib\tslib.js:166:62)
2024-09-09T20:04:01.126 ERROR (pid:45888) [server] - unhandledRejection  Promise {
  <rejected> Error: Windows is not currently supported
      at C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\lib\utils\installer.js:56:19
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\node_modules\tslib\tslib.js:166:62)
} Error: Windows is not currently supported
    at C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\lib\utils\installer.js:56:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\HMB\AppData\Local\coc\extensions\node_modules\coc-lua\node_modules\tslib\tslib.js:166:62)
2024-09-09T20:04:05.501 ERROR (pid:45888) [timing] - activate coc-lua timeout after 5000ms
2024-09-09T20:04:06.935 INFO (pid:45888) [attach] - receive notification: openLog []
```

**Comment by hmmrs** [comment]
Bumped into the same problem.

**Comment by stevenvergenz** [comment]
I've got a workaround for this: don't use coc for lua. You can add it directly by installing lua-language-server to your system path, then adding this to your `init.lua`:

```lua
vim.lsp.config['lua'] = {
	cmd = { 'lua-language-server' },
	filetypes = { 'lua' }
}
vim.lsp.enable('lua')
```
