### ISSUE TITLE
[coc.nvim]: UnhandledRejection: write EPIPE

### ISSUE THREAD

**Issue by Racle** [josa42/coc-lua#80]
After installing `coc-lua` (same issue with `coc-sumenko-lua`), neovim will show these errors when opening .lua files:

```
[coc.nvim]: UnhandledRejection: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at /home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:34:3107
    at new Promise (<anonymous>)
    at WF.write (/home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:34:3028)
    at fC.doWrite (/home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:35:1698)


[coc.nvim]: UnhandledRejection: Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (internal/errors.js:322:7)
    at Socket.Writable.write (internal/streams/writable.js:294:11)
    at /home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:34:3107
    at new Promise (<anonymous>)
    at WF.write (/home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:34:3028)
    at fC.doWrite (/home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:35:1698)
    at /home/username/.local/share/nvim/plugged/coc.nvim/build/index.js:35:1597
```
OS: pop_os 21.10
Neovim: NVIM v0.7.0-dev

**Comment by D4VID0x2** [comment]
Same issue.
Started to happen after updating to coc-lua 1.0.1.
OS: Archlinux
Neovim: NVIM v0.6.1

**Comment by romgrk** [comment]
@josa42 do you have any hints where to look to debug/solve this?

Edit: latest update fixes the issue for me
